[[main]]
  pre = "github"
  name = "GitHub"
  url = "https://github.com/yahav2305/wiki"
  weight = 10

[[main]]
  name = "about"
  pageRef = "about"
  weight = 20

[[main]]
  name = "contact"
  pageRef = "contact"
  weight = 30