deploymentMode: SingleBinary
loki:
  commonConfig:
    replication_factor: 1
  storage:
    type: 'filesystem'
  limits_config:
    retention_period: 720h
  schemaConfig:
    configs:
    - from: "2024-01-01"
      store: tsdb
      index:
        prefix: loki_index_
        period: 24h
      object_store: filesystem
      schema: v13
singleBinary:
  replicas: 1
  persistence:
    storageClass: openebs-hostpath
read:
  replicas: 0
backend:
  replicas: 0
write:
  replicas: 0
chunksCache:
  allocatedMemory: 512
compactor:
  persistence:
    enabled: true
    storageClass: openebs-hostpath
  retention_enabled: true