apiVersion: kiali.io/v1alpha1
kind: Kiali
metadata:
  name: kiali
spec:
  # custom_dashboards:
  # - name: "envoy"
  auth:
    strategy: anonymous
  deployment:
    resources:
      requests:
        memory: "64Mi"
        cpu: "10m"
      limits:
        memory: "500Mi"
        cpu: "1000m"
  spec:
  external_services:
    prometheus:
      # Prometheus service name is "metrics" and is in the "telemetry" namespace
      url: "http://metrics.telemetry:9090/"