name: Production Workflow
on:
  push:
    branches:
    - 'main'
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4
      with:
        submodules: true 
    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v3.0.0
      with:
        hugo-version: '0.127.0'
        extended: true
    - name: Test site build
      run: hugo --minify
    - name: Setup Helm
      uses: azure/setup-helm@v3
      with:
        version: 'v3.15.3'
      id: install
    - name: Lint helm chart
      run: helm lint helm/charts/wiki/ --values helm/values/wiki.yaml
  docker-build-and-push:
    runs-on: ubuntu-22.04
    needs: test
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          submodules: true 
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          version: v0.16.1
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ vars.DOCKERHUB_USERNAME }}/wiki:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
  helm-package-and-push:
    runs-on: ubuntu-22.04
    needs: docker-build-and-push
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4
    - name: Setup Helm
      uses: azure/setup-helm@v3
      with:
        version: 'v3.15.3'
      id: install
    - name: Configure Git
      run: |
        git config user.name "$GITHUB_ACTOR"
        git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
    - name: Package and push helm chart to github pages
      uses: helm/chart-releaser-action@v1.6.0
      with:
        version: v1.6.0
        charts_dir: helm/charts
        pages_branch: helm-charts
      env:
        CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"