name: CICD
on: [push]
jobs:
  test:
    runs-on: ubuntu-22.04
      - # Run tests for every push here
  docker-build-and-push:
    runs-on: ubuntu-22.04
    needs: test
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          version: v3.5.0
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: yahav2305/wiki:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
